Sort complete items based on `sortText`
yegappan/lsp pull request #282
Opened 2023-04-20 15:20 UTC by lithammer

With this, complete items should be sorted in the same way as Visual Studio Code (more or less). Unless the fuzzy matcher is enabled, <del>which then uses `matchfuzzy()` for sorting</del>.

Fixes #281

2023-04-20 15:31 UTC, yegappan commented on autoload/lsp/completion.vim
> +    if empty(d.score)
Can you use `d.score->empty()` here?

2023-04-20 15:32 UTC, yegappan requested changes

2023-04-20 15:32 UTC, yegappan commented on autoload/lsp/completion.vim
> +    sort(completeItems, (a, b) =>
Can you use `completeItems->sort(` here?

2023-04-20 16:17 UTC, andlrc commented
> Unless the fuzzy matcher is enabled, [...]

True.

> [...] which then uses matchfuzzy() for sorting.

I don't think this is really true for `{ autoComplete: true }`. It is for omni completion though.

But don't let that block you. It can always be added later.

2023-04-20 16:21 UTC, andlrc commented on autoload/lsp/completion.vim
> +  if opt.lspOptions.completionMatcher !=? 'fuzzy'
`=#` isn't needed for vim9.

```
:set ignorecase | echo 'Hello' == 'heLLo'
1
:set ignorecase | vim9 echo 'Hello' == 'heLLo'
false
```

Just FYI. The manual also mentions it: `:h expr-!=#` states at the end:

    NOTE: In Vim9 script 'ignorecase' is not used.

2023-04-21 03:37 UTC, merged

2023-04-21 05:06 UTC, yegappan commented on autoload/lsp/completion.vim
> +  if opt.lspOptions.completionMatcher !=? 'fuzzy'
Yes. I missed that note in the help.  I have committed a change to remove `#` from the comparison operators.