Improve signature popup window
yegappan/lsp pull request #448
Opened 2024-01-30 19:58 UTC by girishji

Add 1 character padding to the sides of signature popup window. Otherise, the leftmost character of popup looks like continuation of line from underneath text in some colorschemes. A subtle improvemnt.

M  autoload/lsp/signature.vim

2024-02-01 18:39 UTC, girishji commented
[Correctly handle keys inside symbol popup window](https://github.com/yegappan/lsp/pull/448/commits/aa3777fa2317eedbad00d2b9df73864be7099d87) 

Should have been a separate PR. Didn't know it will just merge 2 commits.

2024-02-03 01:30 UTC, yegappan requested changes

2024-02-03 01:30 UTC, yegappan commented on autoload/lsp/symbol.vim
> +    win_execute(symPopupMenu, 'normal! ' .. "\<C-u>")
Can you use double quotes for the entire string and avoid the string concatenation ".."?

2024-02-03 01:30 UTC, yegappan commented on autoload/lsp/symbol.vim
> +    win_execute(symPopupMenu, 'normal! ' .. "\<C-d>")
Can you use double quotes for the entire string and avoid the string concatenation ".."?

2024-02-03 01:33 UTC, yegappan commented on autoload/lsp/symbol.vim
> +      || key == "\<ScrollWheelUp>"
Can you also update the help text to describe the new keys that can be used in the symbol popup window?

2024-02-05 15:46 UTC, merged